export function distM(a,b,c,d){ const R=6371000, toRad=x=>x*Math.PI/180; const dLa=toRad(c-a), dLo=toRad(d-b); const q=Math.sin(dLa/2)**2+Math.cos(toRad(a))*Math.cos(toRad(c))*Math.sin(dLo/2)**2; return R*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q)) }
export function fechaLaboral(d=new Date()){ const mx = new Date(d.toLocaleString('en-US',{timeZone:'America/Mexico_City'})); if(mx.getHours() < 4) mx.setDate(mx.getDate()-1); return `${mx.getFullYear()}-${String(mx.getMonth()+1).padStart(2,'0')}-${String(mx.getDate()).padStart(2,'0')}` }
export function horaMX(d=new Date()){ return d.toLocaleTimeString('es-MX',{hour12:false,timeZone:'America/Mexico_City'}) }
export function minutos(h){ const mm = h?.toString().match(/(\d{1,2}):(\d{2})/); return mm? parseInt(mm[1])*60+parseInt(mm[2]) : 0 }
export function parseHorarioRango(v){ const s=(v||'').toString().trim(); if(!s) return null; const low=s.toLowerCase(); if(low.includes('libre')||low.includes('flex')) return {entrada:'LIBRE',salida:null,raw:s}; if(low.includes('descanso')) return null; const m=s.match(/(\d{1,2}:\d{2})\s*(?:-|a)?\s*(\d{1,2}:\d{2})?/i); if(!m) return null; return {entrada:m[1],salida:m[2]||null,raw:s} }
export function calcularHorasTrabajadas(hE,hS){ if(!hS) return "8"; const toSeg=h=>{const [hh,mm,ss]=(h||'').split(":").map(Number); return (hh||0)*3600+(mm||0)*60+(ss||0)}; let diff=toSeg(hS)-toSeg(hE); if(diff<0) diff+=24*3600; const h=Math.floor(diff/3600),m=Math.floor((diff%3600)/60); return h===8&&m===0?"8":`${h}:${String(m).padStart(2,'0')}:00` }
export function calcularExtra(hE,hS,pe,ps){ const trab=calcularHorasTrabajadas(hE,hS); if(!pe||!ps||pe==='LIBRE') return {trabajadas:trab,extra:"0",extraMin:0}; const toMin=h=>{const [hh,mm]=h.split(':').map(Number); return (hh||0)*60+(mm||0)}; let mp=toMin(ps)-toMin(pe); if(mp<0) mp+=24*60; let mt=trab==="8"?480:(()=>{const [hh,mm]=trab.split(':').map(Number); return hh*60+mm})(); let ex=mt-mp; if(ex<0) ex=0; return {trabajadas:trab,extra:ex>0?`${Math.floor(ex/60)}:${String(ex%60).padStart(2,'0')}:00`:"0",extraMin:ex} }
export function parseFechaMX(s){ if(!s) return null; if(/^\d{4}-\d{2}-\d{2}$/.test(s)) return new Date(s+'T12:00:00'); const m=s.match(/(\d{1,2})\/(\d{2,4})/); if(m) return new Date(`${m[3].length==2?'20'+m[3]:m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}T12:00:00`); return new Date(s) }
export function normaliza(s){ return (s||'').toString().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim() }
export function getRangoSemana(t){ const hoy=new Date(new Date().toLocaleString('en-US',{timeZone:'America/Mexico_City'})); const d=hoy.getDay(); const lunes=new Date(hoy); lunes.setDate(hoy.getDate()-(d===0?6:d-1)); let l,dom; if(t==='pasada'){l=new Date(lunes); l.setDate(l.getDate()-7); dom=new Date(l); dom.setDate(dom.getDate()+6)}else{l=lunes; dom=hoy} l.setHours(0,0,0,0); dom.setHours(23,59,59,999); return {lunes:l,domingo:dom,rangoTxt:`${l.toLocaleDateString('es-MX')} al ${dom.toLocaleDateString('es-MX')} (${t})`} }
export function sucursalCoincideConFiltro(s,f){ if(!f) return true; const x=(s||'').toLowerCase(); if(f==='coyoacan') return x.includes('coyo')||x.includes('hotel'); if(f==='juarez') return x.includes('juarez')||x.includes('bucareli'); return x.includes(f) }
export function scoreEmpleado(c,d,b){ const cc=normaliza(c), dd=normaliza(d); if(cc===b) return 100; if(cc.startsWith(b)) return 90; if(cc.includes(b)||dd.includes(b)) return 10; return -1 }
export function normalizarProveedor(n){ let x=(n||"").toUpperCase().trim(); if(x.includes("VICTOR HUGO")||x.includes("TRINIDAD")) return null; if(x.includes("GASTRO")) return "GASTROSOPHIA"; if(x.includes("TRES B")||x.includes("3B")) return "TIENDAS TRES B"; if(x.includes("FLORENTINA")) return "QUESOS FLORENTINA"; if(!x||x.length<3) return "PROVEEDOR OCASIONAL"; return x }
